#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 02 23:34:34 MSK 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=photon_v1.3b.zip
