version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
farmersdelight = true
createendertransmission = true
upgrade_aquatic = true
extra_gauges = true
createpropulsion = true
createtransmission = true
s_a_b = true
cbcmodernwarfare = true
crowns = true
cbcmoreshells = true
copycats = true
dndecor = true
ccterminals = true
morered = true
create_sa = true
railways = true
bits_n_bobs = true
cbc_at = true
moonlight = true
tacz = true
fluid = true
ccredstonelinkbridge = true
voltaic = true
create_radar = true
toms_peripherals = true
create_tweaked_controllers = true
offroad = true
createbigcannons = true
cccbridge = true
create_vibrant_vaults = true
vista = true
create = true
aeronautics = true
createcasing = true
simulated = true
interiors = true
advancedperipherals = true
createoreexcavation = true
ballistix = true
struts = true
minecraft = true
easy_villagers = true
azimuth = true
create_connected = true
create_jetpack = true
travelersbackpack = true
createaddition = true
tinymobfarm = true
sliceanddice = true
createframed = true
creeperoverhaul = true
ccbx = true
create_bb = true
computercraft = true
tracks = true
classicperipherals = true
cbc_enhanced_shells = true
aeroworks = true
create_power_loader = true
